[package]
name = "udp-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
termion = "4.0.2"
tokio = { version = "1.40.0", features = ["full"] }
